config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :new, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new]
  end

  resources :posts, only: [:show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:new]
    post 'upvote', to: 'votes#upvote'
    post 'downvote', to: 'votes#downvote'
  end

  resources :comments, only: [:create, :show] do
    post 'upvote', to: 'votes#upvote'
    post 'downvote', to: 'votes#downvote'
  end

  root to: "subs#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :content, :author_id, :post_id, presence: true

  belongs_to :post

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :parent,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :children,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :votes, as: :votable


  def score
    vote_sum = 0
    self.votes.each do |vote|
      vote_sum += vote.value
    end
    vote_sum
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :require_signin

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def show
    @comment = Comment.find_by(id: params[:id])
    @all_comments = @comment.post.comments_by_parent_id
    if @comment
      render :show
    else
      flash[:errors] ||= []
      flash[:errors] << "Could not find comment"
      redirect_to :root
    end
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @comment.errors.full_messages
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_children.html.erb
<li>
  <hr>
  <p>
    <%= link_to comment.author.username, user_url(comment.author) %> <%= comment.created_at %>
  </p>
  <h5> <%= comment.score %> </h5>
  <p>
    <form action="<%= comment_upvote_url(comment.id) %>" method="post">
      <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
      <input type="hidden" name="vote[votable_id]" value="<%= comment.id %>">
      <input type="hidden" name="vote[votable_type]" value="Comment">
      <input type="submit" value="/\">
    </form>
    <form action="<%= comment_downvote_url(comment.id) %>" method="post">
      <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
      <input type="hidden" name="vote[votable_id]" value="<%= comment.id %>">
      <input type="hidden" name="vote[votable_type]" value="Comment">
      <input type="submit" value="\/">
    </form>
    <%= comment.content %>
  </p>
  <p>
    <%= link_to "comments", comment_url(comment) %>
  </p>
  <ul>
    <% all_comments[comment.id].sort_by { |comment| comment.score }.reverse.each do |child| %>
      <%= render "comments/children", comment: child, all_comments: all_comments %>
    <% end %>
  </ul>
</li>

app/views/comments/_form.html.erb
<h5>New comment</h5>
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= comment.post_id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= comment.id %>">
  <label>
    Comment:
    <textarea name="comment[content]" rows="8" cols="40"></textarea>
  </label>
  <input type="submit" value="Submit">
</form>

app/views/comments/new.html.erb
<h5>New comment</h5>
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <label>
    Comment:
    <textarea name="comment[content]" rows="8" cols="40"><%= @comment.content %></textarea>
  </label>
  <input type="submit" value="Submit">
</form>

app/views/comments/show.html.erb
<h3>
  <%= link_to @comment.post.title, post_url(@comment.post) %>
</h3>
<p>
  Author: <%= link_to @comment.author.username, user_url(@comment.author) %> <%= @comment.created_at %>
</p>
<hr>
<h5> <%= @comment.score %> </h5>
<p>
  <form action="<%= comment_upvote_url(@comment.id) %>" method="post">
    <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
    <input type="hidden" name="vote[votable_id]" value="<%= @comment.id %>">
    <input type="hidden" name="vote[votable_type]" value="Commment">
    <input type="submit" value="/\">
  </form>
  <form action="<%= comment_downvote_url(@comment.id) %>" method="post">
    <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
    <input type="hidden" name="vote[votable_id]" value="<%= @comment.id %>">
    <input type="hidden" name="vote[votable_type]" value="Comment">
    <input type="submit" value="\/">
  </form>
<p>
  <%= @comment.content %>
</p>
<hr>
<h5>Comments</h5>
<ul>
  <% @all_comments[@comment.id].each do |comment| %>
    <%= render "children", comment: comment, all_comments: @all_comments %>
  <% end %>
</ul>
<% if current_user %>
  <%= render "form", comment: @comment %>
<% end %>