config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :new, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new]
  end

  resources :posts, only: [:show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:new]
    post 'upvote', to: 'votes#upvote'
    post 'downvote', to: 'votes#downvote'
  end

  resources :comments, only: [:create, :show] do
    post 'upvote', to: 'votes#upvote'
    post 'downvote', to: 'votes#downvote'
  end

  root to: "subs#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_reader :password

  after_initialize :ensure_session_token

  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: { message: "Password cannot be blank" }
  validates :password, length: { minimum: 8, allow_nil: true }

  has_many :moderated_subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Post

  has_many :comments,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Comment

  has_many :votes

  def password=(password)
    @password = password
    pw_dig = BCrypt::Password.create(password)
    self.password_digest = pw_dig
  end

  def is_password?(password)
    pw_dig = BCrypt::Password.new(self.password_digest)
    pw_dig.is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(32)
  end

  def reset_session_token
    self.update(session_token: self.class.generate_session_token)
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user.nil?
      "Error: Username not found"
    elsif user.is_password?(password)
      user
    else
      "Error: Incorrect password"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :already_signedin, only: [:new, :create]
  before_action :require_signin, only: [:show, :destroy]

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user.id != current_user.id
      flash[:errors] ||= []
      flash[:errors] << "You are not the correct user"
      redirect_to :root
    else
      if @user.destroy
        redirect_to :root
      else
        flash[:errors] ||= []
        flash[:errors] << "Could not delete for some reason"
        redirect_to :root
      end
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h3>Create a new user</h3>
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Username:
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <label>
    Password:
    <input type="password" name="user[password]" value="<%= @user.password %>">
  </label>
  <input type="submit" value="Submit">

</form>

app/views/users/show.html.erb
<h3> <%= @user.username %> </h3>
<hr>

<h5>posts</h5>
<table>
  <thead>
    <tr>
      <th>
        title
      </th>
      <th>
        date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @user.posts.each do |post| %>
      <tr>
        <td>
          <%= link_to post.title, post_url(post) %>
        </td>
        <td>
          <%= post.created_at %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>

<h5>subs</h5>
<ul>
  <% @user.moderated_subs.each do |sub| %>
    <li> <%= link_to sub.title, sub_url(sub) %> </li>
  <% end %>
</ul>
<hr>

<%= button_to "delete user", user_url(@user), method: "delete" %>