config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :new, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new]
  end

  resources :posts, only: [:show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:new]
    post 'upvote', to: 'votes#upvote'
    post 'downvote', to: 'votes#downvote'
  end

  resources :comments, only: [:create, :show] do
    post 'upvote', to: 'votes#upvote'
    post 'downvote', to: 'votes#downvote'
  end

  root to: "subs#index"

end

app/models/sub.rb
class Sub < ActiveRecord::Base



  validates :title, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs,
    dependent: :destroy

  has_many :posts,
    through: :post_subs,
    source: :post



end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_signin, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_mod, only: [:edit, :update, :destroy]

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by(id: params[:id])

    if @sub
      @posts = @sub.posts.sort_by { |post| post.score }.reverse
      render :show
    else
      flash[:errors] ||= []
      flash[:errors] << "Could not find requested sub"
      redirect_to :root
    end
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    if @sub
      render :edit
    else
      flash[:errors] ||= []
      flash[:errors] << "Could not find requested sub"
      redirect_to :root
    end
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub
      if @sub.update(sub_params)
        redirect_to sub_url(@sub)
      else
        flash.now[:errors] ||= []
        flash.now[:errors] += @sub.errors.full_messages
        render :edit
      end
    else
      flash[:errors] ||= []
      flash[:errors] << "Could not find requested sub"
      redirect_to :root
    end
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    if @sub
      if @sub.destroy
        redirect_to :root
      else
        flash[:errors] ||= []
        flash[:errors] += @sub.errors.full_messages
        redirect_to sub_url(@sub)
      end
    else
      flash[:errors] ||= []
      flash[:errors] << "Could not find requested sub"
      redirect_to :root
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_mod
    @sub = Sub.find_by(id: params[:id])
    unless @sub.moderator_id == current_user.id
      flash[:errors] ||= []
      flash[:errors] << "You are not authorized to modify this sub"
      redirect_to :root
    end
  end

end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<form action="<%= action == :new ? subs_url : sub_url(sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label>
    Title:
    <input type="text" name="sub[title]" value="<%= sub.title %>">
  </label>
  <label>
    Description:
    <textarea name="sub[description]" rows="8" cols="40"><%= sub.description %></textarea>
  </label>
  <input type="submit" value="Submit">

</form>

app/views/subs/edit.html.erb
<h3> Edit <%= @sub.title %> </h3>
<%= render "form", sub: @sub, action: :edit %>

app/views/subs/index.html.erb
<h3>All subs</h3>
<table>
  <thead>
    <tr>
      <th>
        Sub
      </th>
      <th>
        Description
      </th>
      <th>
        Moderator
      </th>
    </tr>
  </thead>
  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td>
          <%= link_to sub.title, sub_url(sub) %>
        </td>
        <td>
          <%= sub.description %>
        </td>
        <td>
          <%= sub.moderator.username %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Create sub", new_sub_url if current_user %>

app/views/subs/new.html.erb
<h3>Create a new sub</h3>
<%= render "form", sub: @sub, action: :new %>

app/views/subs/show.html.erb
<h3> <%= @sub.title %> </h3>
<h5> Moderator: <%= link_to @sub.moderator.username, user_url(@sub.moderator) %> </h5>
<hr>
<p>
  <%= @sub.description %>
</p>
<hr>
<h5>posts</h5>
<table>
  <thead>
    <tr>
      <th>
        vote
      </th>
      <th>
        title
      </th>
      <th>
        author
      </th>
      <th>
        date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <h5> <%= post.score %> </h5>
          <form action="<%= post_upvote_url(post.id) %>" method="post">
            <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
            <input type="hidden" name="vote[votable_id]" value="<%= post.id %>">
            <input type="hidden" name="vote[votable_type]" value="Post">
            <input type="submit" value="/\">
          </form>
          <form action="<%= post_downvote_url(post.id) %>" method="post">
            <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
            <input type="hidden" name="vote[votable_id]" value="<%= post.id %>">
            <input type="hidden" name="vote[votable_type]" value="Post">
            <input type="submit" value="\/">
          </form>
        </td>
        <td>
          <%= link_to post.title, post_url(post) %>
        </td>
        <td>
          <%= link_to post.author.username, user_url(post.author) %>
        </td>
        <td>
          <%= post.created_at %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<% if current_user %>
  <%= button_to "Make a new post", new_sub_post_url(@sub), method: "get" %>
<% end %>
<% if current_user.id == @sub.moderator_id %>
  <%= button_to "Edit sub", edit_sub_url(@sub), method: "get" %>
  <%= button_to "Delete sub", sub_url(@sub), method: "delete" %>
<% end %>