config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :new, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new]
  end

  resources :posts, only: [:show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:new]
    post 'upvote', to: 'votes#upvote'
    post 'downvote', to: 'votes#downvote'
  end

  resources :comments, only: [:create, :show] do
    post 'upvote', to: 'votes#upvote'
    post 'downvote', to: 'votes#downvote'
  end

  root to: "subs#index"

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :author_id, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs,
    dependent: :destroy

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments

  def comments_by_parent_id
    comments_hash = Hash.new { |h, k| h[k] = [] }
    self.comments.each do |comment|
      comments_hash[comment.parent_comment_id] << comment
    end
    comments_hash
  end

  has_many :votes, as: :votable


  def score
    vote_sum = 0
    self.votes.each do |vote|
      vote_sum += vote.value
    end
    vote_sum
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_signin, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_author, only: [:edit, :update, :destroy]

  def show
    @post = Post.find_by(id: params[:id])
    @all_comments = @post.comments_by_parent_id
    if @post
      render :show
    else
      flash[:errors] ||= []
      flash[:errors] << "Could not find requested post"
      redirect_to :root
    end
  end

  def new
    @post = Post.new
    @current_sub = params[:sub_id]
    @subs = Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @post.errors.full_messages
      @current_sub = params[:sub_id].to_i
      @subs = Sub.all
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    @subs = Sub.all
    if @post
      render :edit
    else
      flash[:errors] ||= []
      flash[:errors] << "Could not find requested post"
      redirect_to :root
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post
      if @post.update(post_params)
        redirect_to post_url(@post)
      else
        flash.now[:errors] ||= []
        flash.now[:errors] += @post.errors.full_messages
        @subs = Sub.all
        render :edit
      end
    else
      flash[:errors] ||= []
      flash[:errors] << "Could not find requested post"
      redirect_to :root
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post
      if @post.destroy
        redirect_to :root
      else
        flash[:errors] ||= []
        flash[:errors] += @post.errors.full_messages
        redirect_to post_url(@post)
      end
    else
      flash[:errors] ||= []
      flash[:errors] << "Could not find requested post"
      redirect_to :root
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def require_author
    @post = Post.find_by(id: params[:id])
    unless @post.author_id == current_user.id
      flash[:errors] ||= []
      flash[:errors] << "You are not authorized to modify this post"
      redirect_to :root
    end
  end

  # Deprecated
  def require_author_or_mod
    @post = Post.find_by(id: params[:id])
    unless @post.author_id == current_user.id || @post.sub.moderator == current_user.id
      flash[:errors] ||= []
      flash[:errors] << "You are not authorized to modify this post"
      redirect_to :root
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<form action="<%= action == :new ? posts_url : post_url(post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input type="hidden" name="post[sub_ids][]" value="<%= current_sub %>" >
  <label>
    Title:
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <label>
    URL:
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  <label>
    Content:
    <textarea name="post[content]" rows="8" cols="40"><%= post.content %></textarea>
  </label>
  <label>
    Crosspost with other subs:
    <% subs.each do |sub| %>
      <% next if sub.id == current_sub.to_i %>
      <label>
        <%= sub.title %>
        <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if post.sub_ids.include?(sub.id) %> >
      </label>
    <% end %>
  </label>
  <input type="submit" value="Submit">

</form>

app/views/posts/edit.html.erb
<h3> Edit <%= @post.title %> </h3>
<%= render "form", post: @post, subs: @subs, current_sub: @current_sub, action: :edit %>

app/views/posts/new.html.erb
<h3>Create a new post</h3>
<%= render "form", post: @post, subs: @subs, current_sub: @current_sub, action: :new %>

app/views/posts/show.html.erb
<h5> <%= @post.score %> </h5>

<h3>
  <form action="<%= post_upvote_url(@post.id) %>" method="post">
    <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
    <input type="hidden" name="vote[votable_id]" value="<%= @post.id %>">
    <input type="hidden" name="vote[votable_type]" value="Post">
    <input type="submit" value="/\">
  </form>
  <form action="<%= post_downvote_url(@post.id) %>" method="post">
    <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
    <input type="hidden" name="vote[votable_id]" value="<%= @post.id %>">
    <input type="hidden" name="vote[votable_type]" value="Post">
    <input type="submit" value="\/">
  </form>
  <%= link_to @post.title, "http://" + @post.url %>
</h3>
<p>
  Author: <%= link_to @post.author.username, user_url(@post.author) %>
</p>
<hr>
<p>
  <%= @post.content %>
</p>
<hr>
<h5>Comments</h5>
<ul>
  <% @all_comments[nil].sort_by { |comment| comment.score }.reverse.each do |comment| %>
    <%= render 'comments/children', comment: comment, all_comments: @all_comments %>
  <% end %>
</ul>
<% if current_user %>
  <%= button_to "Create a comment", new_post_comment_url(@post), method: "get" %>
<% end %>
<% if current_user.id == @post.author_id %>
  <%= button_to "Edit post", edit_post_url(@post), method: "get" %>
  <%= button_to "Delete post", post_url(@post), method: "delete" %>
<% end %>